### ISSUE TITLE
macOS desktop support

### ISSUE THREAD

**Issue by stefandevo** [AngeloAvv/flutter_flavorizr#10]
Hi, first, great package! Very useful!

So I am experimenting with desktop support for flutter, and checked that it seems that macOS support is missing.
As, I think, this is actually almost the same as for iOS, maybe it would be a great idea to add it?

Thx.

**Comment by AngeloAvv** [comment]
Hi @stefandevo , this plugin is mainly intended to easily flavorize mobile applications for android and ios. What do you mean by running flutter for macOS, are you talking about developing apps for Google Fuchsia?

Do you mean that mobile applications (for Android and iOS) are capable of running on macOS, just with a larger screen/resolution?

**Comment by stefandevo** [comment]
Hi @AngeloAvv 

https://flutter.dev/desktop 
https://github.com/flutter/flutter/wiki/Desktop-shells

Desktop support is coming and already running good on MacOs, and will come to Windows, Linux, Fuchsia etc.
Because setup of iOS and MacOs are fairly the same, I think it might be not that difficult to include.

**Comment by AngeloAvv** [comment]
Thanks for the links, I will take a look at it

**Comment by Ahmadre** [comment]
> Thanks for the links, I will take a look at it

Any updates?

**Comment by AngeloAvv** [comment]
We need [this issue](https://github.com/flutter/flutter/issues/64088) to be solved before having flavors on macOS

**Comment by YasinZhou** [comment]
Any updates?

**Comment by jascodes** [comment]
https://github.com/flutter/flutter/issues/64088 has been closed via https://github.com/flutter/flutter/pull/119564

**Comment by AngeloAvv** [comment]
We also need this to tackle macOS flavorizations

https://github.com/flutter/flutter/pull/127997
