### ISSUE TITLE
macOS build doesn't work

### ISSUE THREAD

**Issue by Sergelenchimeg** [AngeloAvv/flutter_flavorizr#106]
Hi! I've implemented this in macOs and first this error occured:

 **Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x202f4deb0) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1045ec4f8). One of the two will be
    used. Which one is undefined.**

  And after fixed this error, run **flutter run --flavor dev -t lib/main_dev.dart** command.
  
  Then result was:
  **The Xcode project defines schemes: dev (Runner project), dev (Runner project), prod (Runner project), prod (Runner project), Runner Exception: You must specify a --flavor option to select one of the available schemes.**

How to run from terminal in macOS? Help me, please.

**Comment by urbanMar** [comment]
@AngeloAvv Any update on macos or windows support for flavours?

**Comment by AngeloAvv** [comment]
Duplicate of #10

**Comment by SergeShkurko** [comment]
i found fix for this problem: https://github.com/AngeloAvv/flutter_flavorizr/issues/217#issuecomment-1771479061
