### ISSUE TITLE
Bump dependencies

### ISSUE THREAD

**Issue by lucavenir** [AngeloAvv/flutter_flavorizr#112]
Hi @AngeloAvv

I'm here asking for a favor. Could you update the dependencies of xml to `xml: ^6.0.0`?

I'm currently facing an conflict issue with another popular package, `flutter_svg`.
Because `flutter_flavorizr >=2.1.0` depends on `xml ^5.3.1` and `flutter_svg 1.1.1+1` depends on `xml ^6.0.1`, I am unable to run `flutter pub get`.

Any workaround is welcome, too.

Thanks!

**Comment by AngeloAvv** [comment]
Hey @lucavenir , yes I can. In the meantime, you could add a dependency_overrides in your pubspec.yaml hoping everything works fine
