### ISSUE TITLE
Different keyStore for different product flavors

### ISSUE THREAD

**Issue by appendixisu** [AngeloAvv/flutter_flavorizr#114]
I follow this document to use. 
https://stackoverflow.com/questions/36194748/different-keystore-for-different-product-flavors-in-gradle

But when rerun flutter_flavorizr, the productFlavors item always on top.

This will cause the build.gradle operation to fail.

**Comment by AngeloAvv** [comment]
Hey @appendixisu, flutter_flavorizr is not meant to be run every time. Due to the actual limitations you need to change the build.gradle file every time you run it

**Comment by thanhhuy0611** [comment]
> Hey @appendixisu, flutter_flavorizr is not meant to be run every time. Due to the actual limitations you need to change the build.gradle file every time you run it

OMG, how can I config CI/CD with this restrict? Any solution?

**Comment by AngeloAvv** [comment]
You can take advantage of [Fastlane](https://fastlane.tools/)

**Comment by gazialankus** [comment]
> Hey @appendixisu, flutter_flavorizr is not meant to be run every time. Due to the actual limitations you need to change the build.gradle file every time you run it

Is this still the case? I could not find references to this in old versions of Readme.md. I guess you have to run flavorizr once to create the flavors and that's it. I wonder if I would have a problem trying to add new flavors down the line when I need to run flavorizr again to create these new flavors.
