### ISSUE TITLE
Asset separation at build time

### ISSUE THREAD

**Issue by AmanMasipeddi** [AngeloAvv/flutter_flavorizr#118]
Hi, I am new to this package an I am have been going through it from yesterday. It is really good and solves my flavor problems. Just a question. Does this package allow to separate the assets(images, etc) and choose them at build time so that not all the assets are available in every flavor apk ?

**Comment by AngeloAvv** [comment]
Hey @AmanMasipeddi , unfortunately this is not possible due to pubspec limitations and how flutter handles assets
