### ISSUE TITLE
Problem When Releasing with Flavours 

### ISSUE THREAD

**Issue by Brinfotech1407** [AngeloAvv/flutter_flavorizr#12]
When i am trying to run my app with flavours via flutter run --flavor <flavorName> -t lib/main-<flavorName>.dart it is working fine but when i am trying to release build  i have encountered the following error
 
**Gradle build failed to produce an .apk file. It's likely that this file was generated under Path , but the tool couldn't find it.**

**Comment by AngeloAvv** [comment]
What instructions are you using to produce an apk file? Please provide further details

**Comment by Brinfotech1407** [comment]
I am running the following command from terminal

flutter build apk

**Comment by AngeloAvv** [comment]
It can't work if you don't specify the flavor.

`flutter build apk --release -t lib/main-apple.dart --flavor apple`

**Comment by Brinfotech1407** [comment]
Okay thanks let me try this

**Comment by AngeloAvv** [comment]
Any updates?

**Comment by Brinfotech1407** [comment]
It's working now , thanks

**Comment by pbayog00** [comment]
What about iOS bundle? The command you wrote is only for apk

Is it mandatory to do it always manually? Using flavorizr forbids using android studio/xcode for generating app bundles?

I think this information about distributing apps with flavorizr should be written in the README of the project

**Comment by AngeloAvv** [comment]
@pbayog00 it works for all kinds of artifacts you want to produce: aab, apk, ipa, and so on.

And yes, you can let it do to your IDE, it's not mandatory to do it through the command line
