### ISSUE TITLE
Flutter targets customization

### ISSUE THREAD

**Issue by mirland** [AngeloAvv/flutter_flavorizr#120]
Right now the library is hardcoding the ios [flutter targets](https://github.com/AngeloAvv/flutter_flavorizr/blob/8254fc48070dc7eaca6ee3b8bb98430a7d2780b5/lib/processors/ios/xcconfig/ios_xcconfig_processor.dart#L67) as `'FLUTTER_TARGET': Variable(value: 'lib/main_$_flavorName.dart'),`. However, in some cases you don't want to change the target, you just want to define the project metadata (bundle id and that stuff)

So, what I'm proposing is do that feature optional.

For example, im my case I'm using these instructions:
```
  instructions:
    - assets:download
    - assets:extract
    - android:buildGradle
    - ios:xcconfig
    - ios:buildTargets
    - ios:schema
    - ios:plist
    - assets:clean
```

As you can see, I'm not creating custom targets. However, `ios:xcconfig` is defining the targets for me.

Propose:
Add a global property to use custom targets or not:
```
flavorizr:
  create_flutter_targets: false
```

**Comment by AngeloAvv** [comment]
Hey @mirland . To achieve what you want you can simply add a variable in the flavorizr configuration. For instance:

``` dart
flavorizr:
  flavors:
    apple:
      app:
        name: "Apple App"

      android:
        applicationId: "com.example.apple"

      ios:
        bundleId: "com.example.apple"
        variables:
          FLUTTER_TARGET:
            value: "lib/main.dart"

    banana:
      app:
        name: "Banana App"

      android:
        applicationId: "com.example.banana"

      ios:
        bundleId: "com.example.banana"
        variables:
          FLUTTER_TARGET:
            value: "lib/main.dart"
```

**Comment by mirland** [comment]
Cool, thanks!
