### ISSUE TITLE
Defining the flavors in a separate config file 

### ISSUE THREAD

**Issue by Petri-Oosthuizen** [AngeloAvv/flutter_flavorizr#123]
The docs indicate that the flavors should be defined in the pubspec.yaml file. Can this instead be defined in a separate file the same why analysis_options can be defined in the pubspec.yaml and in a separate file?

**Comment by AngeloAvv** [comment]
Hey @Petri-Oosthuizen , can you please elaborate on the reasons to prefer putting the config elsewhere?

**Comment by Petri-Oosthuizen** [comment]
Mainly for separation of concerns. The current project I'm working on might have 10+ flavors and I feel like it'll clutter the pubspec.yaml up quite a bit. The project already has analysis_options.yaml, l10n.yaml and flutter_launcher_icons.yaml ([flutter_flavorizr](https://github.com/AngeloAvv/flutter_flavorizr) invalidates this one) in the root of the project and I felt like this would fit nicely alongside the other config files.  

Great work btw.

**Comment by AngeloAvv** [comment]
This change is pretty disruptive. It should be done in a major release. Particularly difficult to address in the short term.
