### ISSUE TITLE
Firebase Setup Empty

### ISSUE THREAD

**Issue by bhavin-concetto** [AngeloAvv/flutter_flavorizr#125]
When I try to generate the flavor using: 

`flutter pub run flutter_flavorizr`

the "Firebase Setup" step was added but it is empty. Is it normal?

<img width="701" alt="Screenshot 2022-09-21 at 5 44 31 PM" src="https://user-images.githubusercontent.com/75062485/191501017-0e2ace10-f18b-439a-91cc-d293917cb36c.png">

**Comment by AngeloAvv** [comment]
Hey @bhavin-concetto definitely not.

Can you provide your flavorizr configuration?

**Comment by BwesShr** [comment]
hi @AngeloAvv  
I have similar issue in implementing firebase in ios side. I have tried google-service.json and GoogleService-Info.plist file in assets file tried it from outside of the project directory. But I keep getting the same error after running `flutter pub run flutter_flavorizr`.

`Executing task google:firebase
Running AndroidFirebaseProcessor
Running AndroidTargetFirebaseProcessor
Running NewFolderProcessor: Creating directory android/app/src/example
Running Copying file from /Volumes/Projects/Flutter/config/google-service.json to android/app/src/example/google-services.json
Unhandled exception:
PathNotFoundException: Cannot copy file to 'android/app/src/example/google-services.json', path = '/Volumes/Projects/Development/Flutter/config/google-service.json' (OS Error: No such file or directory, errno = 2)`

My flavorizr config is 
`flavorizr:
  flavors:
    example1:
      app:
        name: "Example 1"
        icon: assets/logo/example.png

      android:
        applicationId: "com.biwesh.example1"
        firebase:
          config: "/Volumes/Projects/Development/Flutter/config/google-service.json"
        customConfig:
          versionCode: 1
          versionName: "1.0.0"
      ios:
        bundleId: "com.biwesh.example"
        firebase:
          config: "/Volumes/Projects/Development/Flutter/config/example1/GoogleService-Info.plist"

    example2:
      app:
        name: "Example 2"
        icon: assets/logo/example2.png

      android:
        applicationId: "com.biwesh.example2"
        firebase:
          config: "/Volumes/Projects/Development/Flutter/config/google-service.json"
        customConfig:
          versionCode: 1
          versionName: "1.0.0"
      ios:
        bundleId: "com.biwesh.example2"
        firebase:
          config: "/Volumes/Projects/Development/Flutter/config/example2/GoogleService-Info.plist"`
