### ISSUE TITLE
Using Firebase but via flutter fire CLI requires a different approach (I think)

### ISSUE THREAD

**Issue by paulinventome** [AngeloAvv/flutter_flavorizr#127]
So, I am wrapping my head about flavorizr but one of the first stumbling blocks is that firebase seems to now be installed using the flutterfire CLI which generates a firebase_options.dart file. Now I can see how this could be modified to switch options based on flavour manually but in the Xcode build it is adding a firebase_app_id_file.json to the root directory.

So I'm not sure whether I *have* to go through this process for the latest firebase packages or whether google plists can still work (in the docs).

If we do have to move to this process then the question is how we manage the Xcode build side and also whether the android build needs something different. I'm really just starting with firebase so I don't have the experience to know exactly how the thing is set up.

So any help would be most appreciated...

**Comment by paulinventome** [comment]
Okay, thanks for clarifying. 

Are there any plans to support the newest approach? Do I need to regress and manually set up for this project now?

Kindest
Paul

**Comment by paulinventome** [comment]
Sorry following on. Is there any reason that flutter fire couldn't be used but with manual choices of the options file based on the current flavour - seeing as config is all dart based. I don't understand enough about what is going on under the hood to tell this yet?

**Comment by lore-co** [comment]
> Sorry following on. Is there any reason that flutter fire couldn't be used but with manual choices of the options file based on the current flavour - seeing as config is all dart based. I don't understand enough about what is going on under the hood to tell this yet?

No, because the CLI still configure the google_services files
