### ISSUE TITLE
Issue with Flutter 1.20 channel beta and xml plugin.

### ISSUE THREAD

**Issue by bismarabia** [AngeloAvv/flutter_flavorizr#13]
I have upgraded my flutter version to 1.20 channel beta, and I had to upgrade flutter_svg plugin to **0.18.0** to resolve the error. 

Then that plugin flutter_svg comes with another plugin xml whose version is **4.3.0**. But yours has xml version with version **^3.6.1** which cause pub get to fail with the following conflict.

> Because no versions of flutter_flavorizr match >1.0.3 <2.0.0 and flutter_flavorizr 1.0.3 depends on xml ^3.6.1, flutter_flavorizr ^1.0.3 requires xml ^3.6.1.
And because flutter_svg >=0.18.0 depends on xml ^4.1.0, flutter_flavorizr ^1.0.3 is incompatible with flutter_svg >=0.18.0.
So, because MyApp depends on both flutter_svg ^0.18.0 and flutter_flavorizr ^1.0.3, version solving failed.
pub get failed (1; So, because MyApp depends on both flutter_svg ^0.18.0 and flutter_flavorizr ^1.0.3, version solving failed.)

Can you please urgently update xml plugin to **4.3.0** and make a hot-fix release?

**Comment by AngeloAvv** [comment]
If I update the xml plugin to 4.3.0 I will broke the stable channel.

**Comment by AngeloAvv** [comment]
Try adding the following code in your pubspec.yaml file:

```
dependency_overrides:
  xml: ^4.3.0
```

**Comment by bismarabia** [comment]
thank you, I missed the fact that we can make use of dependency_overrides for this kind of situations.

Issue is fixed, 

but I think you adapt your lib for the latest version of flutter.

**Comment by AngeloAvv** [comment]
Yes I know, I always keep xml version 1:1 with the flutter sdk one.

**Comment by AngeloAvv** [comment]
Hi @bismarabia , can you try with the latest version?

**Comment by bismarabia** [comment]
I have tried with latest version, as well as removing the following
```yaml
dependency_overrides:
  xml: ^4.3.0
```

and no problem at all. thanks.

here is my current doctor log.

> [✓] Flutter (Channel beta, 1.20.0-7.3.pre, on Mac OS X 10.15.4 19E287, locale en-TR)
    • Flutter version 1.20.0-7.3.pre at /Users/bisma/Desktop/Flutter/flutter
    • Framework revision e606910f28 (8 days ago), 2020-07-28 16:06:37 -0700
    • Engine revision ac95267aef
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

**Comment by AngeloAvv** [comment]
Ok, I will close this issue, but keep in mind that if someone with the stable channel will report issues I will rollback that.
Thank you.
