### ISSUE TITLE
How to change build folder for ios

### ISSUE THREAD

**Issue by BetterB0y** [AngeloAvv/flutter_flavorizr#141]
When i make command 
flutter build ipa --release --flavor apple -t lib/main_apple.dart --export-method ad-hoc

I want build to be placed at /build/ios/apple/....
Instead of /build/ios/.....
How to achive this?

**Comment by AngeloAvv** [comment]
Unrelaated with flutter_flavorizr:
https://github.com/flutter/flutter/issues/114538
