### ISSUE TITLE
Different Application ID with Flavours and Mode

### ISSUE THREAD

**Issue by Brinfotech1407** [AngeloAvv/flutter_flavorizr#15]
I have two flavors i.e. 
1) Apple
2) Banana 
now suppose for Banana  flavor , if I want to set application id different for release and debug mode is it possible?
means e.g. 
 For Release I want to set app.example.r
 For Debug  I want to set app.example.d

**Comment by AngeloAvv** [comment]
Do you mean iOS Debug/Release or in general?

If you mean in general, you could create four flavors:

- appleDebug
- appleRelease
- bananaDebug
- bananaRelease

it's a little bit redundant on the iOS side but it should work

**Comment by Brinfotech1407** [comment]
I mean in general, but however I want only two flavours it is not possible
right ?

**Comment by AngeloAvv** [comment]
Actually no, and I think it's wrong on Android side. If you want different package names, you should go with different flavors, so in this case I will assume that using four flavors is the right way to do it.
