### ISSUE TITLE
Firebase config phase script wrong

### ISSUE THREAD

**Issue by Klabauterman** [AngeloAvv/flutter_flavorizr#162]
When you use the firebase: and config: parameters to give a flavor its own GoogleService-Info.plist, a phase script gets created for the ios project. Unfortunatly the created phase script does not have an output file defined, so the build fails if there is no file prior to the build. It should define have this in Output files: `$(SRCROOT)/Runner/GoogleService-Info.plist`

**Comment by AngeloAvv** [comment]
Hey @Klabauterman I'm sorry but I don't understand what's the problem. Can you please elaborate?

**Comment by jaeyongjaykim** [comment]
I had the same issue. Building on the local machine works fine, but building on CI/CD pipeline fails.

```
▸ Copying GoogleService-Info.plist

❌  error: Build input file cannot be found: '/Users/runner/work/<project_name>/<project_name>/ios/Runner/GoogleService-Info.plist'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'Runner' from project 'Runner')
```

I have modified the default script and added Input and Output Files to get it to work.

<img width="978" alt="image" src="https://github.com/AngeloAvv/flutter_flavorizr/assets/14931372/385123f5-1c0d-4828-af84-2c31a640db9e">

I hope flavorizr script adds Input and Output files for the iOS Build Phases script.

**Comment by ywake** [comment]
This may be the reason why `ios/Runner/GoogleService-Info.plist` is still an empty file and the following exception may be thrown by `Firebase.initializeApp()` when the app is launched.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [core/not-initialized] Firebase has not been correctly initialized.

Usually this means you've attempted to use a Firebase service before calling `Firebase.initializeApp`.

View the documentation for more information: https://firebase.flutter.dev/docs/overview#initialization

#0      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:120:9)
<asynchronous suspension>
#1      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:31)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#3      main (package:my_app/main.dart:9:3)
<asynchronous suspension>
```

**Comment by vinifig** [comment]
It's not setting the output on add_firebase_build_phase.rb script. I've opened the #248 that fixes this
