### ISSUE TITLE
Seeing an Error on 

### ISSUE THREAD

**Issue by paulinventome** [AngeloAvv/flutter_flavorizr#168]
Just added some extra flavours for a project that had 2 already. Also updated to 2.1.6 and ran flutter pub run flutter_flavorizr

But I am seeing an exception with the plist, but there are no details that help me work out why. I have done a flutter clean, which can often clean up issues.

I'm pasting the error below, is there any way I can find out what the problem is?

help!

Thanks
Paul

[code]
Executing task ios:plist
Unhandled exception:
The following resource is malformed: <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>BGTaskSchedulerPermittedIdentifiers</key>
        <array>
                <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
        </array>
        <key>CADisableMinimumFrameDurationOnPhone</key>
        <true/>
        <key>CFBundleDevelopmentRegion</key>
        <string>$(DEVELOPMENT_LANGUAGE)</string>
        <key>CFBundleExecutable</key>
        <string>$(EXECUTABLE_NAME)</string>
        <key>CFBundleIdentifier</key>
        <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
        <key>CFBundleInfoDictionaryVersion</key>
        <string>6.0</string>
        <key>CFBundleName</key>
        <string>$(BUNDLE_NAME)</string>
        <key>CFBundlePackageType</key>
        <string>APPL</string>
        <key>CFBundleShortVersionString</key>
        <string>$(MARKETING_VERSION)</string>
        <key>CFBundleSignature</key>
        <string>????</string>
        <key>CFBundleURLTypes</key>
        <array>
                <dict>
                        <key>CFBundleTypeRole</key>
                        <string>Editor</string>
                        <key>CFBundleURLName</key>
                        <string>toolbankb2b.com</string>
                        <key>CFBundleURLSchemes</key>
                        <array>
                                <string>b2bapp</string>
                        </array>
                </dict>
        </array>
        <key>CFBundleVersion</key>
        <string>$(FLUTTER_BUILD_NUMBER)</string>
        <key>FlutterDeepLinkingEnabled</key>
        <true/>
        <key>LSRequiresIPhoneOS</key>
        <true/>
        <key>NSCameraUsageDescription</key>
        <string>To scan barcodes for order entry</string>
        <key>UIApplicationSupportsIndirectInputEvents</key>
        <true/>
        <key>UIBackgroundModes</key>
        <array>
                <string>fetch</string>
                <string>processing</string>
                <string>remote-notification</string>
        </array>
        <key>UILaunchStoryboardName</key>
        <string>LaunchScreen</string>
        <key>UIMainStoryboardFile</key>
        <string>Main</string>
        <key>UISupportedInterfaceOrientations</key>
        <array>
                <string>UIInterfaceOrientationPortrait</string>
        </array>
        <key>UISupportedInterfaceOrientations~ipad</key>
        <array>
                <string>UIInterfaceOrientationLandscapeLeft</string>
                <string>UIInterfaceOrientationLandscapeRight</string>
                <string>UIInterfaceOrientationPortrait</string>
                <string>UIInterfaceOrientationPortraitUpsideDown</string>
        </array>
        <key>UIViewControllerBasedStatusBarAppearance</key>
        <false/>
</dict>
</plist>

#0      IOSPListProcessor._updatePListValueAtKey (package:flutter_flavorizr/processors/ios/ios_plist_processor.dart:84:7)
#1      IOSPListProcessor._updateCFBundleDisplayName (package:flutter_flavorizr/processors/ios/ios_plist_processor.dart:63:55)
#2      IOSPListProcessor.execute (package:flutter_flavorizr/processors/ios/ios_plist_processor.dart:48:5)
#3      AbstractFileStringProcessor.execute (package:flutter_flavorizr/processors/commons/abstract_file_string_processor.dart:41:31)
#4      Processor.execute (package:flutter_flavorizr/processors/processor.dart:116:24)
<asynchronous suspension>
[/code]

**Comment by AngeloAvv** [comment]
Hello @paulinventome , can you validate it against [this](https://codebeautify.org/xmlvalidator)?

**Comment by wwnOddbit** [comment]
I'm experiencing the same issue when adding a new flavor and re-running flavorizr. Any suggestions on what we should do/delete before re-running flavorizr?

Thanks for this great package.

**Comment by RYO1223** [comment]
In my environment, `CFBundleDisplayName` is not defined in `ios/Runner/Info.plist`.

I don't know if it wasn't there when I execute `flutter create` or if it was manually deleted at some point, but it worked by adding it manually!

<img width="388" alt="Screenshot 2023-05-24 at 18 54 21" src="https://github.com/AngeloAvv/flutter_flavorizr/assets/70420716/5d93c67a-2a32-49cf-86dd-5ecea99067b6">
