### ISSUE TITLE
Firebase error on IOS

### ISSUE THREAD

**Issue by thiaagodev** [AngeloAvv/flutter_flavorizr#170]
I have been add GoogleService-Info.plist file like this:

ios:
        bundleId: "com.example.myappHomolog"
        firebase:
          config: ".firebase/myapp/GoogleService-Info-MyAppHomolog.plist"
          
But, when i run `flutter run flutter_flavorizr`

And try to run my flavor, this error occurred:

```
Error (Xcode): Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Debug-myapp_homolog-input-files.xcfilelist'

Error (Xcode): Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Debug-myapp_homolog-output-files.xcfilelist'

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.
```

Looks like the flavorizr command not is generating necessary files.

**Comment by Rohithgilla12** [comment]
@thiaagodev this helped me
https://stackoverflow.com/questions/55505991/xcode-10-2-update-issue-build-system-error-1-unable-to-load-contents-of-file-l/56966495#56966495

**Comment by AngeloAvv** [comment]
Hello @thiaagodev , you can't run the flavorizr process using this command: `flutter run flutter_flavorizr`. This command doesn't work and produce 
`Target file "flutter_flavorizr" not found.`

How did you get that error?
