### ISSUE TITLE
Is there a way to access custom defined variable (resValue, variables) inside flutter code.

### ISSUE THREAD

**Issue by UffizioHimanshu** [AngeloAvv/flutter_flavorizr#173]

**Comment by AngeloAvv** [comment]
This has nothing to do with the behavior of flutter_flavorizr. If you need to customize the way your app behaves according to the value of a variable, please define your variables in the F class after running flutter_flavorizr, as mentioned in the [README](https://github.com/AngeloAvv/flutter_flavorizr#customize-your-app).

For further questions, please use the [Discussions](https://github.com/AngeloAvv/flutter_flavorizr/discussions) section.
