### ISSUE TITLE
No such file or directory 

### ISSUE THREAD

**Issue by Geparder** [AngeloAvv/flutter_flavorizr#175]
Running FileProcessor: writing file ios/Runner/GoogleService-Info.plist with nested EmptyFileProcessor
Running ShellProcessor: Running script 'ruby' with arguments .tmp/scripts/ios/add_file.rb, ios/Runner.xcodeproj, Runner/GoogleService-Info.plist
ruby: No such file or directory -- .tmp/scripts/ios/add_file.rb (LoadError)

Running FileProcessor: writing file .tmp/ios/firebaseScript.sh with nested IOSFirebaseScriptProcessor
Running ShellProcessor: Running script 'ruby' with arguments .tmp/scripts/ios/add_firebase_build_phase.rb, ios/Runner.xcodeproj, .tmp/ios/firebaseScript.sh
ruby: No such file or directory -- .tmp/scripts/ios/add_firebase_build_phase.rb (LoadError)

**Comment by henriquetroiano** [comment]
I'm facing the same issue..

**Comment by yacineblr** [comment]
Did you find a solution ?
