### ISSUE TITLE
Is there a way to set up different launchscreens for each flavor in my flutter-flavorizr project?

### ISSUE THREAD

**Issue by qianciling** [AngeloAvv/flutter_flavorizr#176]
I found   [ios:launchScreen](https://github.com/AngeloAvv/flutter_flavorizr#available-instructions)

**But I don't know how to use it, Can you provide a demo？**

`flutter_flavorizr: ^2.1.6`

other
`[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.10.0 on channel stable at /Users/qianciling/develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (3 周前), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/qianciling/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/qianciling/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3
`

**Comment by AngeloAvv** [comment]
Hello @qianciling , a demo project is already available under the example folder.
When you run flutter_flavorizr without customizing the instructions set, the process will create two different launch screens for iOS automatically. After you ran the tool, you can open XCode and customize the launch screens accordingly.

For further questions, please use the [Discussions](https://github.com/AngeloAvv/flutter_flavorizr/discussions) section.

**Comment by qianciling** [comment]
ok. thanks
