### ISSUE TITLE
Issue : file not found.

### ISSUE THREAD

**Issue by AntoineWaes** [AngeloAvv/flutter_flavorizr#180]
Hello,
I keep running issue when executing the command.

Running FileProcessor: writing file .tmp/ios/firebaseScript.sh with nested IOSFirebaseScriptProcessor
Running ShellProcessor: Running script 'ruby' with arguments .tmp/scripts/ios/add_firebase_build_phase.rb, ios/Runner.xcodeproj, .tmp/ios/firebaseScript.sh
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require': **cannot load such file** -- xcodeproj (LoadError)
        from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from .tmp/scripts/ios/add_firebase_build_phase.rb:1:in `<main>'

The rest is working fine, but all the Xcode config files are not generated : 

ruby: No such file or directory -- .tmp/scripts/ios/add_file.rb (LoadError)

Could you help ?

here is the config file : 

flavorizr:
  ide: "vscode"
  flavors:
    roomvi_dev:
      app:
        name: "-----"
    
      android:
        applicationId: "------"
        firebase:
          config: "firebase/dev/google-services.json"
    
      ios:
        bundleId: "------"
        firebase:
          config: "firebase/dev/GoogleService-Info.plist"
    
    roomvi:
      app:
        name: "-----"
        
      android:
        applicationId: "------"
        firebase:
          config: "firebase/prod/google-services.json"
      ios:
        bundleId: "-----"
        firebase:
          config: "firebase/prod/GoogleService-Info.plist"

**Comment by AntoineWaes** [comment]
Updates : I've updated gem, home-brew and Xcode 
Now, I've got this error : 

.tmp/scripts/ios/add_build_configuration.rb:23:in `<main>': undefined method `build_settings' for nil:NilClass (NoMethodError)

build_config.build_settings = base_config.build_settings.clone

**Comment by AngeloAvv** [comment]
Hey @AntoineWaes , what's the output of `xcodeproj --version`?

**Comment by duchv-nws** [comment]
I same error
xcode 14.2
flutter 3.10

**Comment by takekapp1990** [comment]
Hi. I had the same error and found solution for me.

I encountered the error when I run below:
```
flutter pub run flutter_flavorizr -p ios:xcconfig
#console out: ruby: No such file or directory -- .tmp/scripts/darwin/add_file.rb (LoadError)
``` 
**Solution:** 

Get all the needed files from assets and run target action:
```
flutter pub run flutter_flavorizr -p assets:download assets:extract ios:xcconfig assets:clean
# (assets:clean is optional.)
``` 
reference: 
https://github.com/AngeloAvv/flutter_flavorizr/blob/80e8967e035d7d3a23a3733cfcdcb45508c6d000/lib/src/processors/processor.dart

**Comment by devkirch** [comment]
@takekapp1990 Hi, i face the same issue. I  dont quite understand your Solution. What do you mean by get all the needed files? Your Command does not help in my case.

**Comment by takekapp1990** [comment]
@devkirch 
Hi. You can get all the needed files by setting `assets:download` process as below. Then, set some process you need like `ios:xcconfig` and so on. Lastly, you can delete downloaded files by setting `assets:clean`.
```
flutter pub run flutter_flavorizr -p assets:download assets:extract ios:xcconfig assets:clean
# (assets:clean is optional.)
```

**Comment by devkirch** [comment]
@takekapp1990 Thank you, I already fixed my problem. I had custom instructions where the assets:clean was run right after the assets:download, which obviously deletes the files.

**Comment by isacmoura** [comment]
If none of the above solutions works for you (my case), I tried the following:  
My problem started when I tried to add Firebase processor with the command `flutter pub run flutter_flavorizr -p google:firebase`. Then I got the error `Unhandled exception:
Exception: ruby: No such file or directory -- .tmp/scripts/darwin/add_file.rb (LoadError)`.  For solving this:  

1. Generated the assets with `flutter pub run flutter_flavorizr -p assets:download assets:extract -p google:firebase`. I got the same error but a zipped file named `assets.tmp.zip` was generated in the root of the project.
2. I extracted this file and renamed the `tmp` folder to `.tmp`.
3. Run the command again: `flutter pub run flutter_flavorizr -p google:firebase`

**Comment by calvinandhika** [comment]
> Updates : I've updated gem, home-brew and Xcode Now, I've got this error :
> 
> .tmp/scripts/ios/add_build_configuration.rb:23:in `<main>': undefined method `build_settings' for nil:NilClass (NoMethodError)
> 
> build_config.build_settings = base_config.build_settings.clone

any luck in fixing this issue?

**Comment by Chezlui** [comment]
> 1. flutter pub run flutter_flavorizr -p assets:download assets:extract

Man, this answer from @isacmoura worked like magic... why isn't the standard behaviour?

**Comment by AngeloAvv** [comment]
> > 1. flutter pub run flutter_flavorizr -p assets:download assets:extract
> 
> Man, this answer from [@isacmoura](https://github.com/isacmoura) worked like magic... why isn't the standard behaviour?

It is, but if you override the processor list, you have to define them manually

**Comment by Chezlui** [comment]
Hi @AngeloAvv , 

Thanks for your answer.

By overriding I guess you mean using the "-p" command and choosing which of the https://github.com/AngeloAvv/flutter_flavorizr?tab=readme-ov-file#default-processors-set processors you want to use.

Am I right?

If that the case, and by doing that an error/exception can happen it would be pretty helpful if you could add a warning here: https://github.com/AngeloAvv/flutter_flavorizr?tab=readme-ov-file#usage

In my case, I thought that choosing specific processors was "the way to go". For instance I had my icons so I didn't find value on downloading "placeholder assets" that I wasn't going to use, so I skip those.

Actually I am new to iOS and I thought the errors was due to a previous inconsistent state of my schemes/build configurations respect to what flavorizr was expecting to find. And not that I was skipping some steps by using the "-p" alternative.

I hope that helps
