### ISSUE TITLE
flutter_flavorizr regenerates all the dart files

### ISSUE THREAD

**Issue by imsujan276** [AngeloAvv/flutter_flavorizr#183]
I have used the flutter_flavorizr package to generate the prod and dev versions of the app, and it works great. 

But the issue is, every time I run the command `flutter pub run flutter_flavorizr`, it regenerates/adds all the default dart files. The changes in `main.dart` and `flavors.dart` are lost. 

Is there any way to stop regenerating the dart files?

**Comment by AngeloAvv** [comment]
Duplicate of #9

**Comment by imsujan276** [comment]
Seems like this issue is there since 2020.
