### ISSUE TITLE
Very long build time

### ISSUE THREAD

**Issue by holland-hng** [AngeloAvv/flutter_flavorizr#185]
Hi @AngeloAvv

Application build time is pushed up very high. Initially, my app took less than 20s to build the first time and only 15s for the second. However, after using flavor it took 150s the first time and 60s the second time.

I know that your flavor library already generates scripts to copy the config files before runtime. However, I don't think that makes the build time so long.

There may be some problems in my project but hope to get your answer to this question.

**Comment by holland-hng** [comment]
I remembered that while creating the flavor I added firebase to the app. maybe that makes my app slow to build

**Comment by AngeloAvv** [comment]
Hello @holland-hng , I don't think flutter_flavorizr has anything to do with the building time. Of course the more you add dependencies, the longer the app will take to build

**Comment by holland-hng** [comment]
@AngeloAvv 

Thanks for your respond
This problem occurs when I integrate firebase ios sdk into the project, it's really too heavy.
