### ISSUE TITLE
AndroidBuildGradleProcessor not idempotent

### ISSUE THREAD

**Issue by MrTarantula** [AngeloAvv/flutter_flavorizr#19]
After running several times I noticed that `android/app/build.gradle` contains several `flavorDimensions` and `productFlavors` sections. It appears that `AndroidBuildGradleProcessor` does not check if those sections exist before appending.

Just something to keep in mind when you work on gradle file parsing.

**Comment by AngeloAvv** [comment]
Yeah I know, I didn't find a good groovy/gradle parser, so I'm still thinking about how to solve this issue. Actually it's better to run the flavorizer once.
