### ISSUE TITLE
Google firebase service file location

### ISSUE THREAD

**Issue by beetechsoln** [AngeloAvv/flutter_flavorizr#195]
Where is the fisebase file located in the below code. As  I have tried to keep it in the assets file. But it created the empty google service file and I am unable to receive the firbase notification

assets:
    - firebase/apple/
    - firebase/banana/

flavors:
  apple:
    app:
      name: "Apple"
  
    android:
      applicationId: "com.example.apple"
      firebase:
        config: "firebase/apple/google-services.json"
  
    ios:
      bundleId: "com.example.apple"
      firebase:
        config: "firebase/apple/GoogleService-Info.plist"
  
  banana:
    app:
      name: "Banana"
      
    android:
      applicationId: "com.example.banana"
      firebase:
        config: "firebase/banana/google-services.json"
    ios:
      bundleId: "com.example.banana"
      firebase:
        config: "firebase/banana/GoogleService-Info.plist"

I get this resposnse  
Building package executable... 
Built flutter_flavorizr:flutter_flavorizr.
Executing task google:firebase
Running IOSTargetsFirebaseProcessor
Running FileProcessor: writing file ios/Runner/GoogleService-Info.plist with nested EmptyFileProcessor
Running ShellProcessor: Running script 'ruby' with arguments .tmp/scripts/ios/add_file.rb, ios/Runner.xcodeproj, Runner/GoogleService-Info.plist
Running FileProcessor: writing file .tmp/ios/firebaseScript.sh with nested IOSFirebaseScriptProcessor
Running ShellProcessor: Running script 'ruby' with arguments .tmp/scripts/ios/add_firebase_build_phase.rb, ios/Runner.xcodeproj, .tmp/ios/firebaseScript.sh

**Comment by AngeloAvv** [comment]
There's something wrong with your instruction set: according to your output, you're missing some processors to be executed before running google:firebase.

**Comment by beetechsoln** [comment]
I did run other porcessors before running google:firebase
flutter pub run flutter_flavorizr -p assets:download

**Comment by AngeloAvv** [comment]
`assets:extract` is missing also

**Comment by beetechsoln** [comment]
okay This is what I get after adding that code 
flutter pub run flutter_flavorizr -p assets:download,assets:extract,google:firebase,assets:clean
Deprecated. Use `dart run` instead.
Building package executable... 
Built flutter_flavorizr:flutter_flavorizr.
Executing task assets:download

Executing task assets:extract

Executing task google:firebase
Running IOSTargetsFirebaseProcessor
**Running FileProcessor: writing file ios/Runner/GoogleService-Info.plist with nested EmptyFileProcessor**
Running ShellProcessor: Running script 'ruby' with arguments .tmp/scripts/ios/add_file.rb, ios/Runner.xcodeproj, Runner/GoogleService-Info.plist
Running FileProcessor: writing file .tmp/ios/firebaseScript.sh with nested IOSFirebaseScriptProcessor
Running ShellProcessor: Running script 'ruby' with arguments .tmp/scripts/ios/add_firebase_build_phase.rb, ios/Runner.xcodeproj, .tmp/ios/firebaseScript.sh

Executing task assets:clean
Running Deleting file from assets.tmp.zip
Running Deleting file from .tmp

**Comment by AngeloAvv** [comment]
How can flavors work if you don't customize the whole project by calling the others processors?

You're missing `android:`, `flutter:` and `ios:` processors

I don't understand why you're executing the process by removing default processors.

**Comment by beetechsoln** [comment]
I just want to create the ios GoogleService-Info file for different falvor for FCM to work. The command `flutter pub run flutter_flavorizr` is not creating GoogleService-Info files for different falvor rather its GoogleService-Info file in which i have replaced with one of the GoogleService-Info file. 

> Where is the fisebase file located in the below code. As I have tried to keep it in the assets file. But it created the empty google service file and I am unable to receive the firbase notification
> 
> assets: - firebase/apple/ - firebase/banana/
> 
> flavors: apple: app: name: "Apple"
> 
> ```
> android:
>   applicationId: "com.example.apple"
>   firebase:
>     config: "firebase/apple/google-services.json"
> 
> ios:
>   bundleId: "com.example.apple"
>   firebase:
>     config: "firebase/apple/GoogleService-Info.plist"
> ```
> 
> banana: app: name: "Banana"
> 
> ```
> android:
>   applicationId: "com.example.banana"
>   firebase:
>     config: "firebase/banana/google-services.json"
> ios:
>   bundleId: "com.example.banana"
>   firebase:
>     config: "firebase/banana/GoogleService-Info.plist"
> ```
> 
> I get this resposnse Building package executable... Built flutter_flavorizr:flutter_flavorizr. Executing task google:firebase Running IOSTargetsFirebaseProcessor Running FileProcessor: writing file ios/Runner/GoogleService-Info.plist with nested EmptyFileProcessor Running ShellProcessor: Running script 'ruby' with arguments .tmp/scripts/ios/add_file.rb, ios/Runner.xcodeproj, Runner/GoogleService-Info.plist Running FileProcessor: writing file .tmp/ios/firebaseScript.sh with nested IOSFirebaseScriptProcessor Running ShellProcessor: Running script 'ruby' with arguments .tmp/scripts/ios/add_firebase_build_phase.rb, ios/Runner.xcodeproj, .tmp/ios/firebaseScript.sh
