### ISSUE TITLE
'flavorDimensions' is deprecated

### ISSUE THREAD

**Issue by wujek-srujek** [AngeloAvv/flutter_flavorizr#200]
As in the title, the snippet generated for Android (Groovy syntax) uses a deprecated property:
```groovy
flavorDimensions "a", "b"
```

**Comment by rfaturriza** [comment]
Use `flavorDimensions ['a', 'b']`

**Comment by AngeloAvv** [comment]
Hey @wujek-srujek can you please take a look [here](https://github.com/AngeloAvv/flutter_flavorizr/pull/220) to see if the problem is solved? Thanks

**Comment by wujek-srujek** [comment]
The deprecation warning is gone and the app starts fine as well. Thanks.
