### ISSUE TITLE
How to turn off processors?

### ISSUE THREAD

**Issue by subzero911** [AngeloAvv/flutter_flavorizr#225]
flavorizr always generates default App widget and Pages folder; I don't need it.
I suppose that I should turn off the following processors:
```
flutter:app
flutter:pages
```
How can I do it?

It also overwrites my main.dart with its custom content, I want to turn it off too, but leave main_dev.dart and main_prod.dart.

**Comment by burakoztermt** [comment]
I ran into same situation when I realized that this package creates a lot of files and overwrites the existing ones.

 So here is what I did; I copied all the default processors [Processors Set](https://github.com/AngeloAvv/flutter_flavorizr#default-processors-set) and delete the ones I don't need. E.g. `flutter:app` and `flutter:pages` . No pages created and app.dart was not overwritten.

**Comment by subzero911** [comment]
> I ran into same situation when I realized that this package creates a lot of files and overwrites the existing ones.
> 
> So here is what I did; I copied all the default processors [Processors Set](https://github.com/AngeloAvv/flutter_flavorizr#default-processors-set) and delete the ones I don't need. E.g. `flutter:app` and `flutter:pages` . No pages created and app.dart was not overwritten.

Can I read processors from file somehow, to not to enter them in a command line one by one?

**Comment by AngeloAvv** [comment]
> > I ran into same situation when I realized that this package creates a lot of files and overwrites the existing ones.
> > So here is what I did; I copied all the default processors [Processors Set](https://github.com/AngeloAvv/flutter_flavorizr#default-processors-set) and delete the ones I don't need. E.g. `flutter:app` and `flutter:pages` . No pages created and app.dart was not overwritten.
> 
> Can I read processors from file somehow, to not to enter them in a command line one by one?

Yes, you can. You can specify a custom set of instructions as mentioned in the [README](https://amzn.to/3MITz2B). Here's a list of instructions: https://github.com/AngeloAvv/flutter_flavorizr#available-instructions

Keep in mind some of them are mandatory to make other instructions work properly.

**Comment by burakoztermt** [comment]
> > > I ran into same situation when I realized that this package creates a lot of files and overwrites the existing ones.
> > > So here is what I did; I copied all the default processors [Processors Set](https://github.com/AngeloAvv/flutter_flavorizr#default-processors-set) and delete the ones I don't need. E.g. `flutter:app` and `flutter:pages` . No pages created and app.dart was not overwritten.
> > 
> > 
> > Can I read processors from file somehow, to not to enter them in a command line one by one?
> 
> Yes, you can. You can specify a custom set of instructions as mentioned in the [README](https://github.com/AngeloAvv/flutter_flavorizr#flavorizr). Here's a list of instructions: https://github.com/AngeloAvv/flutter_flavorizr#available-instructions
> 
> Keep in mind some of them are mandatory to make other instructions work properly.

Cool, looks like you can! @subzero911. 
 
Added instructions array in the .yaml file and it works.
``` 
instructions: [
   "assets:download",
   "assets:extract",
   ...
]
```

Maybe add this to the examples with the default set? people can easily add more or remove instructions instead default is used implicitly.

**Comment by AngeloAvv** [comment]
> Maybe add this to the examples with the default set? people can easily add more or remove instructions instead default is used implicitly.

It's already written in the README here: https://github.com/AngeloAvv/flutter_flavorizr#default-processors-set
