### ISSUE TITLE
Facing Issue when running my flavors with Android Studio IDE Play Button

### ISSUE THREAD

**Issue by Brinfotech1407** [AngeloAvv/flutter_flavorizr#23]
Below is my configuration for running my dev Flavor

![image](https://user-images.githubusercontent.com/66242900/91324348-9878d380-e7df-11ea-84de-e4c1be1924d5.png)

And I am facing the below issue 

![image](https://user-images.githubusercontent.com/66242900/91324563-d8d85180-e7df-11ea-92bd-efc70581f9d9.png)

**Comment by AngeloAvv** [comment]
Did you put additional arguments to the configuration?

I cannot reproduce your issue, I created a new project following my example (and also setting the studio IDE) and it works fine in Android Studio.

**Comment by lucasdidur** [comment]
@Brinfotech1407 You don't need to add 'Additional Arguments' to flavor if you are using 'Build flavor'.
