### ISSUE TITLE
Gradle build failed to produce an .apk file. It's likely that this file was generated under

### ISSUE THREAD

**Issue by jpaulo789b** [AngeloAvv/flutter_flavorizr#25]
`flutter run --flavor FlavorA -t lib/main-FlavorA.dart --verbose`

output 
`Exception: Gradle build failed to produce an .apk file. It's likely that this file was generated under /home/harlock/Documents/projetos/treino/build, but the tool
couldn't find it.`

flutter doctor -v

[✓] Flutter (Channel unknown, 1.20.0, on Linux, locale pt_BR.UTF-8)
    • Flutter version 1.20.0 at /home/harlock/development/flutter
    • Framework revision 840c9205b3 (5 weeks ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/harlock/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /home/harlock/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/harlock/android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.0

[✓] Connected device (1 available)
    • Mi 9 Lite (mobile) • 77b94361 • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by AngeloAvv** [comment]
Hi @jpaulo789b , can you please provide the build.gradle file under android/app? Just hide the package names using ****

**Comment by jpaulo789b** [comment]
android/build.gradle
`buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
        maven{
     url 'https://sdk.uxcam.com/android/'
  }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`
android/app/build.gradle

`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '15'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.4'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {

    flavorDimensions "flavor-type"

    productFlavors {
        FlavorA{
            dimension "flavor-type"
            applicationId "br.com.***"
            resValue "string", "app_name", "Flavor A"
        }
        FlavorB {
            dimension "flavor-type"
            applicationId "br.com.***"
            resValue "string", "app_name", "Flavor B"
        }
        FlavorC {
            dimension "flavor-type"
            applicationId "*****"
            resValue "string", "app_name", "Flavor C"
        }
    }

    compileSdkVersion 28
    signingConfigs {
        release_si {
            storeFile file('../../.cert/***.key')
            storePassword '****'
            keyAlias = '*****'
            keyPassword '*****'
        }
    }
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "br.com.***"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
         multiDexEnabled true
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release_si
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:multidex:1.0.3'
}

apply plugin: 'com.google.gms.google-services'

`

**Comment by jpaulo789b** [comment]
Hello, the files below

`android/build.gradle`

                buildscript {
                    ext.kotlin_version = '1.3.50'
                    repositories {
                        google()
                        jcenter()
                        maven{
                    url 'https://sdk.uxcam.com/android/'
                }
                    }

                    dependencies {
                        classpath 'com.android.tools.build:gradle:3.5.0'
                        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
                        classpath 'com.google.gms:google-services:4.3.0'
                    }
                }

                allprojects {
                    repositories {
                        google()
                        jcenter()
                    }
                }

                rootProject.buildDir = '../build'
                subprojects {
                    project.buildDir = "${rootProject.buildDir}/${project.name}"
                }
                subprojects {
                    project.evaluationDependsOn(':app')
                }

                task clean(type: Delete) {
                    delete rootProject.buildDir
                }


`android/app/build.gradle`

            def localProperties = new Properties()
            def localPropertiesFile = rootProject.file('local.properties')
            if (localPropertiesFile.exists()) {
                localPropertiesFile.withReader('UTF-8') { reader ->
                    localProperties.load(reader)
                }
            }

            def flutterRoot = localProperties.getProperty('flutter.sdk')
            if (flutterRoot == null) {
                throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
            }

            def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
            if (flutterVersionCode == null) {
                flutterVersionCode = '15'
            }

            def flutterVersionName = localProperties.getProperty('flutter.versionName')
            if (flutterVersionName == null) {
                flutterVersionName = '1.4'
            }

            apply plugin: 'com.android.application'
            apply plugin: 'kotlin-android'
            apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

            android {

                flavorDimensions "flavor-type"

                productFlavors {
                    FlavorA {
                        dimension "flavor-type"
                        applicationId "com.*****"
                        resValue "string", "app_name", "FlavorA"
                    }
                    FlavorB {
                        dimension "flavor-type"
                        applicationId "com.*****.*****"
                        resValue "string", "app_name", "FlavorB"
                    }
                    FlavorC {
                        dimension "flavor-type"
                        applicationId "com.*****.*****"
                        resValue "string", "app_name", "FlavorC"
                    }
                }

                compileSdkVersion 28
                signingConfigs {
                    release_treino {
                        storeFile file('../../.cert/*****.key')
                        storePassword '****'
                        keyAlias = '*****'
                        keyPassword '*****'
                    }
                }
                sourceSets {
                    main.java.srcDirs += 'src/main/kotlin'
                }

                lintOptions {
                    disable 'InvalidPackage'
                }

                defaultConfig {
                    // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
                    applicationId "br.com.*****"
                    minSdkVersion 19
                    targetSdkVersion 28
                    versionCode flutterVersionCode.toInteger()
                    versionName flutterVersionName
                    multiDexEnabled true
                }

                buildTypes {
                    release {
                        // TODO: Add your own signing config for the release build.
                        // Signing with the debug keys for now, so `flutter run --release` works.
                        signingConfig signingConfigs.release_treino
                    }
                }
            }

            flutter {
                source '../..'
            }

            dependencies {
                implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
                implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
                implementation 'com.android.support:multidex:1.0.3'
            }

            apply plugin: 'com.google.gms.google-services'

**Comment by jpaulo789b** [comment]
[SOLVED] 
the name of the flavors should start with a lowercase
`flavorA instead of FlavorA`
