### ISSUE TITLE
vscode integration issue

### ISSUE THREAD

**Issue by danielwalczak** [AngeloAvv/flutter_flavorizr#27]
After I run vscode preprocessor I'm not able to run e.g 'prod Debug'

```
Set the 'program' value in your launch config (eg 'lib/main.dart') then launch again
```

I have to add  manually "program": "lib/main-prod.dart" into launch.json

**Comment by AngeloAvv** [comment]
Hi @danielwalczak , I don't use Visual Studio code, we need to ask for help to @MrTarantula

**Comment by MrTarantula** [comment]
@danielwalczak What do your `pubspec.yaml` and `.vscode/launch.json` look like after you run flavorizr? What's your OS?

**Comment by jawa0919** [comment]
> 运行 vscode 预处理器后，我无法运行例如“prod Debug”
> 
> ```
> Set the 'program' value in your launch config (eg 'lib/main.dart') then launch again
> ```
> 
> 我必须手动添加 "program": "lib/main-prod.dart" 到 launch.json

```
{
  // 使用 IntelliSense 了解相关属性。
  // 悬停以查看现有属性的描述。
  // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "flutter_app",
      "request": "launch",
      "type": "dart"
    },
    {
      "name": "flutter_app apple",
      "request": "launch",
      "type": "dart",
      "program": "${workspaceFolder}/lib/main_apple.dart",
      "args": ["--flavor", "apple"]
    },
    {
      "name": "flutter_app banana",
      "request": "launch",
      "type": "dart",
      "program": "${workspaceFolder}/lib/main_banana.dart",
      "args": ["--flavor", "banana"]
    }
  ]
}
```
