### ISSUE TITLE
Only for Android issue [The following fields were missing: [flavors]. Read the docs for further details]

### ISSUE THREAD

**Issue by jk-hub** [AngeloAvv/flutter_flavorizr#271]
> Error: The following fields were missing: [flavors]. Read the docs for further details

Here is the Code for the yaml file 

`
flavorizr:
  ide: "vscode"
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    development:
      app:
        name: "Bharti Dev"

      android:
        applicationId: "com.dev.example.app"
        icon: "assets/png/app_logo.png"
      ios:
        bundleId: ""

    staging:
      app:
        name: "Bharti Qa"

      android:
        applicationId: "com.staging.example.app"
        icon: "assets/png/app_logo.png"
      ios:
        bundleId: ""

    production:
      app:
        name: "Bharti"

      android:
        applicationId: "com.example.app"
        icon: "assets/png/app_logo.png"
      ios:
        bundleId: ""
    instructions:
      - android:androidManifest
      - android:buildGradle
      - android:dummyAssets
      - android:icons
      - flutter:flavors
      - flutter:app
      - flutter:targets
`

**Comment by AngeloAvv** [comment]
Can you please fix your flavor format? I strongly believe you indented it the wrong way and that's why you get that error

**Comment by jk-hub** [comment]
This is the format from were i have copied from 
<img width="438" alt="Screenshot 2024-06-27 at 12 15 46 PM" src="https://github.com/AngeloAvv/flutter_flavorizr/assets/58223882/628daa02-72c1-4bf9-babf-5b0e5f7629c2">

**Comment by jk-hub** [comment]
Now I'm getting this error 


Building package executable... 
Built flutter_flavorizr:flutter_flavorizr.
type 'YamlList' is not a subtype of type 'Map<dynamic, dynamic>' in type cast

**Comment by jk-hub** [comment]
I got my fix by removed this below instructions and by fix my flavor format

instructions:
  - android:androidManifest
  - android:buildGradle
  - android:dummyAssets
  - android:icons
  - flutter:flavors
  - flutter:app
  - flutter:targets
  
  @AngeloAvv  you can close this issue Thanks for the help
