### ISSUE TITLE
Rerunning `flutter pub run flutter_flavorizr` recreates main.dart

### ISSUE THREAD

**Issue by mikemilla** [AngeloAvv/flutter_flavorizr#276]
Hey, maybe I am the only one getting this, or I may be doing something wrong, but rerunning `flutter pub run flutter_flavorizr` will destroy my `main.dart`, remove all my code in it and recreate the file.

The flow I want to use is every now and then rerun the command because I add a new api key or something else. Just want to recreate my flavor files and what not. Not nuke my `main.dart`.

Any help is useful. Thanks

**Comment by kmrosiek** [comment]
it also recreates `pages/` `flavors.dart` `app.dart` and modifies other mains by changing import from `import 'package:common/flavors/flavors.dart';` to `import 'flavors.dart';` How to prevent that?

**Comment by lucapan** [comment]
Same issue here. It would be nice to avoid overwriting main.dart and app.dart. Thanks!

**Comment by AngeloAvv** [comment]
Hello @mikemilla , [as mentioned](https://github.com/AngeloAvv/flutter_flavorizr?tab=readme-ov-file#default-processors-set) in the README, you have to redefine your set of processors if you want to skip some of them.
[Here](https://github.com/AngeloAvv/flutter_flavorizr?tab=readme-ov-file#available-instructions) you can find a brief description of what each processor does.
