### ISSUE TITLE
Archiving not working correctly

### ISSUE THREAD

**Issue by Toq97** [AngeloAvv/flutter_flavorizr#31]
Hello @AngeloAvv, awesome package! it is very useful!

I configured correctly in android and i am able to create two different apk with different identifiers.
But the same thing is not happening on ios. if i try to archive with apple scheme, it will arhive successfuly but he is taking the identifiers of banana.
how can i create 2 different archive for banana and apple?

**Comment by AngeloAvv** [comment]
Hi @Toq97 , did you select the correct scheme from the dropdown menu on the right side of the play button?

**Comment by Toq97** [comment]
yes, i selected the scheme i want to archive.

Same things is happening when i am triying to do: flutter build ios --release --flavor apple.

He is taking identifier of banana.

i founded a workaround selecting my scheme release config on comand-line builds. but this will not work if a want to use ci with fastlane.

**Comment by WieFel** [comment]
@Toq97 flutter beta channel offers the command `flutter build ipa`. See [here](https://github.com/flutter/flutter/issues/13065#issuecomment-714749994). Hopefully this will soon land in the stable channel.

Using the command `flutter build ipa --flavor <flavor> -t lib/main-<flavor>.dart` I was able to build an IPA that works correctly and is now deployed on app store ;)

**Comment by Toq97** [comment]
@WieFel That would be awesome .. no need of open xCode
i will take a look on this and see if it working correctly with fastlane

**Comment by AngeloAvv** [comment]
@Toq97 can you please check if this issue still exists in 1.0.11?

**Comment by Kedar-27** [comment]
> @Toq97 can you please check if this issue still exists in 1.0.11?

+1

**Comment by Kedar-27** [comment]
This issue...still exists!!

**Comment by zeshuaro** [comment]
@Kedar-27 I was able to archive the iOS app properly by setting the appropriate config for command-line builds. See screenshot below:

![Screen Shot 2021-06-24 at 11 46 27 pm](https://user-images.githubusercontent.com/12210067/123274008-79a1b580-d546-11eb-97c3-96774cd3683d.png)
