### ISSUE TITLE
No iOS simulators/devices showing up for flavor schemes in Xcode

### ISSUE THREAD

**Issue by WieFel** [AngeloAvv/flutter_flavorizr#33]
I just created a fresh flutter project and set up `flutter_flavorizr` according to the steps described in the `README.md`. I set up two flavors "apple" and "banana".
The app runs fine on Android and also on iOS simulator using the `flutter run ...` command from a terminal.

However, when opening the `ios/` folder in Xcode I am not able to run/build the "apple" or "banana" scheme. I don't get any devices displayed for the two flavor schemes (image showing apple scheme):
![image](https://user-images.githubusercontent.com/8345062/100464714-615fda00-30ce-11eb-96ef-a77dfe01645f.png)

When trying the default "Runner" scheme simulators are displayed just like normal:
![image](https://user-images.githubusercontent.com/8345062/100464802-87857a00-30ce-11eb-83c7-03c4925a6351.png)

Also following the advice of https://github.com/AngeloAvv/flutter_flavorizr/issues/17#issuecomment-729133185 didn't help with this problem.

Does anyone have any hint?

**Comment by Ahmadre** [comment]
cc/ @AngeloAvv
