### ISSUE TITLE
 The Xcode project does not define custom schemes. You cannot use the --flavor option.

### ISSUE THREAD

**Issue by suraj740** [AngeloAvv/flutter_flavorizr#35]
When running on ios simulator, getting the above error.
which custom schemas we have to define?

**Comment by Hanggi** [comment]
How did you solved this problem?

**Comment by AngeloAvv** [comment]
If flutter_flavorizr hasn't generated the schemes it means only one thing: you haven't installed Xcodeproj gem or (if you are working with version control) you haven't added and committed your .xcscheme files.

**Comment by Hanggi** [comment]
> If flutter_flavorizr hasn't generated the schemes it means only one thing: you haven't installed Xcodeproj gem or (if you are working with version control) you haven't added and committed your .xcscheme files.

I had xcodeproj installed, but it was not through gem, that was the problem.
Thank you.

**Comment by m-skolnick** [comment]
For anyone else coming across this, run `sudo gem install xcodeproj`, then run `flutter pub run flutter_flavorizr` again.
