### ISSUE TITLE
Custom variables for each flavor

### ISSUE THREAD

**Issue by danielwalczak** [AngeloAvv/flutter_flavorizr#36]
Is it possible to create custom variables, similar to 'bundleId' so I can use it inside info.plist file?
The main purpose is to use it for the dynamic links config, but Im pretty sure everyone can have different use case.

```
	<key>FirebaseDynamicLinksCustomDomains</key>
	<array>
		<string>https://custom.link.flavor</string>
	</array>
```

**Comment by krishnakumarcn** [comment]
Did you found any workaround for this for the time being? Can we define variables like $(BUNDLE_NAME) on XCode?

@danielwalczak

**Comment by AngeloAvv** [comment]
> Did you found any workaround for this for the time being? Can we define variables like $(BUNDLE_NAME) on XCode?
> 
> @danielwalczak

You can define them in your xcconfig files.

**Comment by muccy** [comment]
The problem is that any modification to xcconfig is overwritten at next `flutter pub run flutter_flavorizr`

**Comment by AngeloAvv** [comment]
You shouldn't run it every time. It is supposed to be run once and only once for how it is conceived. Anyway we'll figure a way out.

**Comment by muccy** [comment]
Thank you very much. Maybe I'm simply misusing the tool or the tool is not suited for the job. Anyway, very nice work :)
