### ISSUE TITLE
Support for Null Safety?

### ISSUE THREAD

**Issue by gabxap** [AngeloAvv/flutter_flavorizr#37]
Is support for null safety coming to this package?

**Comment by AngeloAvv** [comment]
HI @gabxap , we need to wait for some libraries to fully migrate to nullsafety. I'm currently stuck due to build_runner library

**Comment by AngeloAvv** [comment]
Done in https://github.com/AngeloAvv/flutter_flavorizr/releases/tag/v2.0.0
