### ISSUE TITLE
json_annotation dependency upgrade?

### ISSUE THREAD

**Issue by wizawuza** [AngeloAvv/flutter_flavorizr#42]
I know the full upgrade to null safety may be difficult due to build_runner, but is it possible to partially upgrade by upgrading for json_annotation ^4.0.1? It's helpful with the freezed lib upgrade.

Thank you very much for the awesome package.

**Comment by AngeloAvv** [comment]
json_annotation 4.x.x is written using nullsafety, so it won't be compatible with the current version of flutter_flavorizr.
