### ISSUE TITLE
How to build specifically for android only

### ISSUE THREAD

**Issue by jain-aayush1123** [AngeloAvv/flutter_flavorizr#45]
The documentation says that we need to run a custom set of instructions to build specifically for android. But I couldn't find those anywhere. Its a pretty good library and I want to use it but cant find the instructions

**Comment by AngeloAvv** [comment]
Hello @jain-aayush1123 , they are defined in the README here: https://github.com/AngeloAvv/flutter_flavorizr#default-processors-set
