### ISSUE TITLE
Build APK Error (Android)

### ISSUE THREAD

**Issue by girish54321** [AngeloAvv/flutter_flavorizr#47]
Hi Thanks for this amazing package but i m facing some problems with build 

Error screenshot 

<img width="987" alt="Screenshot 2021-04-24 at 8 26 40 PM" src="https://user-images.githubusercontent.com/47414322/115963328-7d13c300-a53c-11eb-8d77-d4dbde4a7678.png">

**Comment by AngeloAvv** [comment]
This problem is not related to the library, but it's more like a Gradle problem. To fix this problem, you should build the prod flavor before the dev one.

**Comment by girish54321** [comment]
Thanks @AngeloAvv will try this.
