### ISSUE TITLE
flutter web

### ISSUE THREAD

**Issue by kiaxseventh** [AngeloAvv/flutter_flavorizr#49]
hello dear
Do you have any plans to support flutter web ?

**Comment by AngeloAvv** [comment]
Hi @kiaxseventh , since Flutter doesn't really want to support flavors for Flutter web it's a bit tricky to manage all the surrounding stuff directly by flutter_flavorizr. Anyway, it's still possible to launch custom targets after you flavorized your project

**Comment by rafagazani** [comment]
you can use dart-define, example:
flutter build web --dart-define FLAVOR="you-flavor"

inside the app:
  const flavor =String.fromEnvironment('FLAVOR', defaultValue: 'you-flavor');

**Comment by yogikorke** [comment]
> Hi @kiaxseventh , since Flutter doesn't really want to support flavors for Flutter web it's a bit tricky to manage all the surrounding stuff directly by flutter_flavorizr. Anyway, it's still possible to launch custom targets after you flavorized your project

Hi Sir, I am able to run web app with flavors but not able to build web app with flavors, is there any solution for this.

**Comment by cedvdb** [comment]
related https://github.com/flutter/flutter/issues/141371
