### ISSUE TITLE
Different assets for flavors

### ISSUE THREAD

**Issue by dvird** [AngeloAvv/flutter_flavorizr#53]
Hi,

I have 5 flavours and each flavor has a big background image.
I have "assets/" folder in my project with the 5 images and when I compile one flavour it contains all the background of all apps.

how can I set assets only for specific flavor?

**Comment by AngeloAvv** [comment]
You can't actually differentiate assets based on flavors. You have to keep all of them in the assets folder and then reference them according to the current flavor (you can customize which one to pick by defining a custom method in the generated flavors.dart file)

There's a workaround but it has nothing to do with this library: you can set up a pre-build script that copies the right files from another source and paste them into the assets folder according to the current flavor scheme.
