### ISSUE TITLE
Cannot open file, path = '.tmp/ios/firebaseScript.sh' 

### ISSUE THREAD

**Issue by rodrigorafaeldamaceno** [AngeloAvv/flutter_flavorizr#54]
Hello, thanks for this package, it saved me a lot of time.

I try to add firebase to an existing project and I get this error.

obs. GoogleService-Info.plist has been successfully copied to the iOS project.

`Running FileProcessor: writing file ios/Runner/GoogleService-Info.plist with nested EmptyFileProcessor
Running ShellProcessor: Running script 'ruby' with arguments .tmp/scripts/ios/add_file.rb, ios/Runner.xcodeproj, Runner/GoogleService-Info.plist
Running FileProcessor: writing file .tmp/ios/firebaseScript.sh with nested IOSFirebaseScriptProcessor
Unhandled exception:
FileSystemException: Cannot open file, path = '.tmp/ios/firebaseScript.sh' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#4      AbstractFileStringProcessor.execute (package:flutter_flavorizr/processors/commons/abstract_file_string_processor.dart:40:15)
#5      QueueProcessor.execute (package:flutter_flavorizr/processors/commons/queue_processor.dart:39:17)
#6      QueueProcessor.execute (package:flutter_flavorizr/processors/commons/queue_processor.dart:39:17)
#7      Processor.execute (package:flutter_flavorizr/processors/processor.dart:106:24)
#8      execute (package:flutter_flavorizr/flutter_flavorizr.dart:54:13)
#9      main (file:///Users/rodrigo/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_flavorizr-2.0.0/bin/flutter_flavorizr.dart:4:3)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
pub finished with exit code 255`

**Comment by AngeloAvv** [comment]
Hi @rodrigorafaeldamaceno , can you please past your pubspec.yaml content?

**Comment by rodrigorafaeldamaceno** [comment]
Hi @AngeloAvv, of course.

`flutter_flavorizr: ^2.0.0

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    sicredi:
      app:
        name: "Sicredi"
      android:
        applicationId: "com.neocred.sicredi"
        firebase:
          config: ".firebase/sicredi/google-services.json"
      ios:
        bundleId: "com.neocred.sicredi"
        firebase:
          config: ".firebase/sicredi/GoogleService-Info.plist"
    cresol:
      app:
        name: "Cresol"
      android:
        applicationId: "com.neocred.cresol"
        firebase:
          config: ".firebase/cresol/google-services.json"
      ios:
        bundleId: "com.neocred.cresol"
        firebase:
          config: ".firebase/cresol/GoogleService-Info.plist"
    neocred:
      app:
        name: "Neocred"
      android:
        applicationId: "com.swa.neocred"
        firebase:
          config: ".firebase/neocred/google-services.json"
      ios:
        bundleId: "com.swa.neocred"
        firebase:
          config: ".firebase/neocred/GoogleService-Info.plist"`

**Comment by PhanithNoch** [comment]
hello, @rodrigorafaeldamaceno did you solved it I'm facing the same issue help, please?

**Comment by AngeloAvv** [comment]
Hi @rodrigorafaeldamaceno , I've tested your pubspec configuration on my PCs twice and it went smoothly. Sounds like a problem with permissions or something that has to do with your ruby setup. It's not library-related.

**Comment by RaduGrama** [comment]
I had to run `mkdir .tmp/ios` to get over that error. I didn't investigate further what is causing it.

**Comment by rodrigorafaeldamaceno** [comment]
I created the .tmp/ios folder manually and the script worked, thanks.
