### ISSUE TITLE
I'm getting issue when run flutter pub run flutter_flavorizr

### ISSUE THREAD

**Issue by PhanithNoch** [AngeloAvv/flutter_flavorizr#55]
Running AndroidTargetFirebaseProcessor
Running NewFolderProcessor: Creating directory android/app/src/uat
Running Copying file from .firebase/uat/google-services.json to android/app/src/uat/google-services.json
Unhandled exception:
FileSystemException: Cannot copy file to 'android/app/src/uat/google-services.json', path = '.firebase/uat/google-services.json' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.copySync (dart:io/file_impl.dart:340:5)
#2      CopyFileProcessor.execute (package:flutter_flavorizr/processors/commons/copy_file_processor.dart:37:26)
#3      QueueProcessor.execute (package:flutter_flavorizr/processors/commons/queue_processor.dart:39:17)
#4      QueueProcessor.execute (package:flutter_flavorizr/processors/commons/queue_processor.dart:39:17)
#5      QueueProcessor.execute (package:flutter_flavorizr/processors/commons/queue_processor.dart:39:17)
#6      Processor.execute (package:flutter_flavorizr/processors/processor.dart:106:24)
<asynchronous suspension>
pub finished with exit code 255

**Comment by AngeloAvv** [comment]
Hi @PhanithNoch , did you put the google-services.json file here? 

`.firebase/uat/google-services.json`

**Comment by amitmeh10** [comment]
Hi , i am also facing this issue. Do you guys have any solution ?

**Comment by PhanithNoch** [comment]
firebase:
          config: "ios/firebase/uat/GoogleService-Info.plist"
        firebase:
          config: "android/app/firebase/uat/google-services.json"

**Comment by PhanithNoch** [comment]
> Hi @PhanithNoch , did you put the google-services.json file here?
> 
> `.firebase/uat/google-services.json`

**Comment by kiptoomm** [comment]
> Hi @PhanithNoch , did you put the google-services.json file here?
> 
> `.firebase/uat/google-services.json`

Hi @AngeloAvv, it would be nice if this were in the documentation somewhere because I was also left guessing for a while about how/where I should obtain this directory. 


I have manually created the `.firebase` folder with the following contents:
```
$ ls .firebase

.firebase//dev:
GoogleService-Info.plist google-services.json

.firebase//stg:
GoogleService-Info.plist google-services.json
```

However, upon running `flutter pub run flutter_flavorizr` I'm seeing this error:

```
...
Executing task google:firebase
Running AndroidFirebaseProcessor
Running AndroidTargetFirebaseProcessor
Running NewFolderProcessor: Creating directory android/app/src/dev
Running Copying file from .firebase/dev/google-services.json to android/app/src/dev/google-services.json
Running AndroidTargetFirebaseProcessor
Running NewFolderProcessor: Creating directory android/app/src/stg
Running Copying file from .firebase/stg/google-services.json to android/app/src/stg/google-services.json
Running IOSTargetsFirebaseProcessor
Running IOSFirebaseProcessor
Running NewFolderProcessor: Creating directory ios/Runner/dev
Running Copying file from .firebase/dev/GoogleService-Info.json to ios/Runner/dev/GoogleService-Info.plist
Unhandled exception:
FileSystemException: Cannot copy file to 'ios/Runner/dev/GoogleService-Info.plist', path = '.firebase/dev/GoogleService-Info.json' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.copySync (dart:io/file_impl.dart:340:5)
#2      CopyFileProcessor.execute (package:flutter_flavorizr/processors/commons/copy_file_processor.dart:37:26)
#3      QueueProcessor.execute (package:flutter_flavorizr/processors/commons/queue_processor.dart:39:17)
#4      QueueProcessor.execute (package:flutter_flavorizr/processors/commons/queue_processor.dart:39:17)
#5      QueueProcessor.execute (package:flutter_flavorizr/processors/commons/queue_processor.dart:39:17)
#6      Processor.execute (package:flutter_flavorizr/processors/processor.dart:106:24)
<asynchronous suspension>
pub finished with exit code 255
```

What is `GoogleService-Info.json`? I thought that for iOS we only should need GoogleService-Info.plist
