### ISSUE TITLE
Problem with build apk in release mode [also in example]

### ISSUE THREAD

**Issue by MeloJR** [AngeloAvv/flutter_flavorizr#58]
Hi! I have tried to build an apk from a flavor but it fails. Because of I thought it was my fault I made a new project from scratch with `flutter create`, added the `flutter_flavorizr` dependency and ran `flutter pub run flutter_flavorizr`.
With this setup if I run the command `flutter build apk --flavor banana -t lib/main-banana.dart` it works well but if I try to build the other flavor (`flutter build apk --flavor apple -t lib/main-apple.dart`) it fails. Here are the traces:
```
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:lintVitalAppleRelease'.                 
> Could not resolve all artifacts for configuration ':app:bananaReleaseRuntimeClasspath'.
   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /Users/jfb/Development/test_project/build/app/intermediates/flutter/bananaRelease/libs.jar.
         > Transform's input file does not exist: /Users/jfb/Development/test_project/build/app/intermediates/flutter/bananaRelease/libs.jar.
```
It seems that try to find in the intermediates files a file corresponding to the banana flavor, not apple.

Am I doing something wrong? Thanks in advance.

**Comment by AngeloAvv** [comment]
Duplicates of #47. It's a gradle/Flutter problem with the apk build generation. It's not involved with the flavorizr.

If you build every target one by one before creating an apk, it work flawlessly

**Comment by MeloJR** [comment]
Sorry, I didn't find that issue. Thank you! It works!
