### ISSUE TITLE
how to customize app icon (both android and IOS)?

### ISSUE THREAD

**Issue by axilaris** [AngeloAvv/flutter_flavorizr#7]
I posted in here as well:
https://stackoverflow.com/questions/62439565/flutter-variant-flavors-using-flutter-flavorizr-how-to-customize-app-icon-bot

I am trying to figure out how to use flutter_flavorizr to make different variant apps with the same code based.

Here are some documentations that I have been trying to refer: https://pub.dev/packages/flutter_flavorizr#-readme-tab- https://medium.com/@angeloavv/easily-build-flavors-in-flutter-android-and-ios-with-flutter-flavorizr-d48cbf956e4

So far, I cant find much information/example detailing on customizing the app icon for the different apps (essentially its needed for both Android and IOS).

My question is how can I use flutter_flavorizr to customize the appicons for the different variant apps ? Is that possible

**Comment by AngeloAvv** [comment]
flutter_flavorizr is designed to create the structure of the flavors. The further customizations are up to you. Once you have generated the flavors structure, you have to put (or replace if you haven't disabled the dummy asset generator) the icons in the res folder (for Android) and in the xcassets file (for iOS) manually.

That's how it actually works, I don't know if I will implement more specific processors to fully customize these processes in the future.

**Comment by axilaris** [comment]
that is fine with the assets and code.

what about the app_id and bundle_id. Its specified in the pubspec.yaml but does it generate different apps with the specified ids ? 

i think thats important for variant creation.

**Comment by axilaris** [comment]
maybe lets close this. as the assets are indeed generated for the different flavors. thanks.

on the app_id and bundle_id, I find it weird its not created. I post it here: https://github.com/AngeloAvv/flutter_flavorizr/issues/8
