### ISSUE TITLE
Flavour limitations ?

### ISSUE THREAD

**Issue by tmlrsn53gmx** [AngeloAvv/flutter_flavorizr#75]
Can you elaborate about the limitations and restriction of this package , (e.g) can we generate build more than 300 apps separate  android and ios build ? if  yes means, any issues may happened in future ?  can we use this package for SAAS kind of application  build

**Comment by AngeloAvv** [comment]
Please use the [Discussions](https://github.com/AngeloAvv/flutter_flavorizr/discussions) section to ask questions.
