### ISSUE TITLE
flutter_flavorizr cannot create separate app with different app_id/bundle_id for creating variant in flutter

### ISSUE THREAD

**Issue by axilaris** [AngeloAvv/flutter_flavorizr#8]
posted here as well: https://stackoverflow.com/questions/62466186/flutter-flavorizr-cannot-create-separate-app-with-different-app-id-bundle-id-for

- Runner.xcworkspace - there is only one (shouldnt it be different mandarin/arabic)
- I'ved pubspec.yaml according to flutter_flavorizr specifying the different flavors appid/bundleid
- in the screenshot, you could see an empty bundle id in xcode

flutter_flavorizr cannot create different apps with different app_id / bundle_id ?

**Comment by AngeloAvv** [comment]
Just a few question, why using different flavors for different languages? Flavors are intended to satisfy a product lineup, for internationalisation you should follow this one: https://flutter.dev/docs/development/accessibility-and-localization/internationalization

No, a flavor process creates a single app with multiple configurations, so a single Runner is enough, as you can see in the project example.

How are you opening the iOS project? Are you referencing the xcworkspace file instead of the xcproj one?

**Comment by axilaris** [comment]
@AngeloAvv its not internationalization that I required. My purpose is to create different variant apps so it will be different apps in the appstore. (same code base, different icons, different appid/bundleid, some flavouring in the themes and different language)

There is the pubspec.yaml that you specify Apple and Banana app with the application_id and bundle_id, its not affected in the ios and android project ? I think this is fundamental for creating different flavors&variant.

**Comment by axilaris** [comment]
> How are you opening the iOS project? Are you referencing the xcworkspace file instead of the xcproj one?
I open xcode with Runner.xcworkspace

**Comment by AngeloAvv** [comment]
Actually your screenshot appears exactly as mine. I don't understand what's your problem. To run different flavors you simply need to select the configuration from the dropdown menu next to the Play button in XCode, or by running the 

flutter run --flavor <flavorName> -t lib/main-<flavorName>.dart

command from the shell with an already opened iOS emulator.

**Comment by axilaris** [comment]
the problem is this https://i.stack.imgur.com/TjKR7.png

com.example.mandarin / com.example.arabic is not applied in the Android or IOS project

is that the behaviour ?

**Comment by AngeloAvv** [comment]
The flutter_flavorizr tool does not creates multiple projects. It creates a flavor configuration, have you ever flavorized a project manually?

I suggest you to read these before start using this library

https://flutter.dev/docs/deployment/flavors
