### ISSUE TITLE
Application Name Internationalization And Warning About Naming

### ISSUE THREAD

**Issue by LinHaoLove** [AngeloAvv/flutter_flavorizr#85]
I think it is necessary to support the internationalization of single flavor application names. But I didn't find where to fill in. In addition, if there is an underscore in the file name, there will be a warning in Android Studio. If it is changed to an underscore, there will be no warning.
Thank you for your attention to these words.

**Comment by LinHaoLove** [comment]
In addition to some file naming, there are warnings for the naming of attributes or enumerations

**Comment by AngeloAvv** [comment]
Hello @LinHaoLove , can you please elaborate on your concerns about internationalization?

**Comment by LinHaoLove** [comment]
It's a pleasure to hear from you。
Let me give you an example：
flavorizer1: 苹果、Apple，and so on.
flavorizer2: 香蕉、Banana, and so on.


When I switch between different&nbsp;flavorizers, I want to display the corresponding internationalization name.Not a fixed name.
If there are different&nbsp;flavorizers, different startup interfaces can be set. That's better.


I'm sorry I'm not good at English.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AngeloAvv/flutter_flavorizr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月3日(星期天) 凌晨1:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AngeloAvv/flutter_flavorizr] Application Name Internationalization And Warning About Naming (Issue #85)





 
Hello @LinHaoLove , can you please elaborate on your concerns about internationalization?

**Comment by AngeloAvv** [comment]
@LinHaoLove after you ran the flavorizr, you can customize the app_name directly in strings.xml according to the destination language for Android and using a custom .plist file for iOS.

**Comment by LinHaoLove** [comment]
Thank you for your reply.
I fully understand what you're saying, but that's not what I want.
My company has changed the requirements, so it no longer needs such a mechanism.
Have a nice day.
