### ISSUE TITLE
CFBundleDisplayName is not replaced by $(BUNDLE_NAME) variable

### ISSUE THREAD

**Issue by dJani97** [AngeloAvv/flutter_flavorizr#97]
Hi!

I'm flavorizing an existing app, and I've noticed that the `CFBundleDisplayName` property in the Info.plist file didn't get replaced by the respectable variable. I had to change it manually.

It worked well on Android, so I expected it to work out-of-the-box on iOS too.

flutter_flavorizr: ^2.1.3

I'm happy to provide further information if necessary.

**Comment by AngeloAvv** [comment]
Hi @dJani97 , according to the [official documentation](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundledisplayname), you should use CFBundleDisplayName only if your app name is longer than the CFBundleName. Can you please elaborate your thoughts?

**Comment by WingCH** [comment]
https://stackoverflow.com/a/15423880/5588637

if preset `$(BUNDLE_NAME) ` to CFBundleDisplayName property  in the Info.plist, i think is better
