### ISSUE TITLE
Problem while running processor set google:firebase

### ISSUE THREAD

**Issue by nandhakumargdr** [AngeloAvv/flutter_flavorizr#99]
Hi,

I have tried to add firebase configuration to the application, but there are problems while running google:firebase processor.

It seems some script file is missing. could you please fix this issue

Please see the log messages below.

![Screenshot 2022-04-06 at 7 18 38 PM](https://user-images.githubusercontent.com/31739695/161991155-70081955-3491-455f-a55c-4f288c73e398.png)

**Comment by AngeloAvv** [comment]
Hi @nandhakumargdr , google:firebase needs some preprocessors to be executed before like assets:download and assets:extract

**Comment by nandhakumargdr** [comment]
Awesome, it is working!
